---
driver:
  name: vagrant
  network:
  - ["private_network", {ip: "172.16.0.1"}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[hanlon::default]
    attributes:
