name 'hanlon'
maintainer ''
maintainer_email ''
license ''
description 'Installs/Configures hanlon'
long_description 'Installs/Configures hanlon'
version '0.1.0'

depends 'apt'
depends 'yum'
depends 'yum-epel'
depends 'ruby_build'
depends 'tftp'
depends 'runit'
